server.port=8080
debug=true

# userService
spring.cloud.gateway.routes[0].id=user
spring.cloud.gateway.routes[0].uri=http://localhost:8002
spring.cloud.gateway.routes[0].predicates[0]=Path=/userservices/**
spring.cloud.gatewat.routes[0].filters[0]=AuthenticationFilter

# carService
spring.cloud.gateway.routes[1].id=car
spring.cloud.gateway.routes[1].uri=http://localhost:8003
spring.cloud.gateway.routes[1].predicates[0]=Path=/car/**,/brand/**,/category/**
spring.cloud.gatewat.routes[1].filters[0]=AuthenticationFilter

# componentsService
spring.cloud.gateway.routes[2].id=components
spring.cloud.gateway.routes[2].uri=http://localhost:8005
spring.cloud.gateway.routes[2].predicates[0]=Path=/components/**
spring.cloud.gatewat.routes[2].filters[0]=AuthenticationFilter

# bookingService
spring.cloud.gateway.routes[3].id=booking
spring.cloud.gateway.routes[3].uri=http://localhost:8004
spring.cloud.gateway.routes[3].predicates[0]=Path=/booking/**
spring.cloud.gatewat.routes[3].filters[0]=AuthenticationFilter
